In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [5]:
# https://jalammar.github.io/visual-numpy/

In [6]:
my_list = [10,20,30,40]

In [7]:
type(my_list)

list

In [8]:
np.array(my_list)

array([10, 20, 30, 40])

In [9]:
my_numpy_array = np.array(my_list)

In [10]:
type(my_numpy_array)

numpy.ndarray

In [13]:
my_numpy_array.max()

np.int64(40)

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.random.random(5)

array([0.22845759, 0.30495888, 0.40393983, 0.07140705, 0.66782906])

In [17]:
# array arithmetic

In [18]:
my_list1 = [1,2]

In [21]:
my_list2 = [2,3]

In [22]:
my_list1 + my_list2

[1, 2, 2, 3]

In [23]:
my_numpy_array1 = np.array(my_list1)

In [24]:
my_numpy_array2 = np.array(my_list2)

In [25]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [26]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [27]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [28]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [29]:
my_numpy_array1 * 5

array([ 5, 10])

In [30]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [31]:
other_array = np.array([10,20,30,40,50])

In [32]:
other_array.min()

np.int64(10)

In [33]:
other_array.sum()

np.int64(150)

In [34]:
my_numpy_array1

array([1, 2])

In [35]:
other_array

array([10, 20, 30, 40, 50])

In [36]:
my_numpy_array1 + other_array

ValueError: operands could not be broadcast together with shapes (2,) (5,) 

In [37]:
# arange & indexing

In [38]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
np_array = np.arange(0,10)

In [43]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np_array[0]

np.int64(0)

In [45]:
np_array[-1]

np.int64(9)

In [46]:
np_array[1:4:]

array([1, 2, 3])

In [47]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
np_array[2:6:2]

array([2, 4])

In [49]:
# random

In [50]:
np.random.randn(4)

array([-1.25649585, -1.35857096,  0.78011125,  0.57858724])

In [51]:
np.random.randn(4,4)

array([[ 0.41248495, -0.59649135,  0.9845451 ,  0.46332627],
       [-0.56231481, -0.16225232,  1.01864705,  1.50935278],
       [-1.11548351, -1.2813887 , -0.2177521 ,  0.21453147],
       [-0.69165226, -0.97948758, -1.35134729, -0.96714959]])

In [52]:
np.random.randint(1,300,5)

array([208,  64, 151, 167, 160], dtype=int32)