In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [5]:
# https://jalammar.github.io/visual-numpy/

In [6]:
my_list = [10,20,30,40]

In [7]:
type(my_list)

list

In [8]:
np.array(my_list)

array([10, 20, 30, 40])

In [9]:
my_numpy_array = np.array(my_list)

In [10]:
type(my_numpy_array)

numpy.ndarray

In [13]:
my_numpy_array.max()

np.int64(40)

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.random.random(5)

array([0.22845759, 0.30495888, 0.40393983, 0.07140705, 0.66782906])

In [ ]:
# array arithmetic