In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10], [15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][1]

10

In [32]:
# row -> sıra * column -> kolon
# row by column

In [8]:
numpy_matrix = np.array([[5,10], [15,20]])

In [9]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix[1][0]

np.int64(15)

In [13]:
numpy_matrix.sum()

np.int64(50)

In [14]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.random.random((3,2))

array([[0.07112491, 0.18768025],
       [0.05491724, 0.67636057],
       [0.81040184, 0.79314078]])

In [18]:
# matrix arithmetic

In [19]:
first_array = np.array([[10,20], [30,40]])

In [20]:
second_array = np.array([[5,15],[25,35]])

In [21]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [22]:
third_array = np.array([[50,60]])

In [23]:
third_array

array([[50, 60]])

In [24]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [25]:
fourth_array = np.array([[10,20,30,40,50]])

In [26]:
first_array + fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (1,5) 

In [27]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [28]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [29]:
third_array = np.array([[10], [20]])

In [30]:
third_array

array([[10],
       [20]])

In [31]:
third_array.shape

(2, 1)

In [33]:
first_array.shape

(2, 2)

In [34]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [35]:
first_array

array([[10, 20],
       [30, 40]])

In [36]:
# matrix multiplication

In [37]:
first_array

array([[10, 20],
       [30, 40]])

In [38]:
second_array

array([[ 5, 15],
       [25, 35]])

In [39]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [40]:
# dot product

In [42]:
# matrix dimension = 1x3 3x2 = 1x2 -> dot product yapılabilmesi için sol tarafın son sayısı yani kolon sayısıyla sağ tarafın ilk sayısı
# yani satır sayısı eşit olmalıdır.

In [43]:
first_matrix = np.array([[10,20,30]])

In [44]:
first_matrix

array([[10, 20, 30]])

In [45]:
first_matrix.shape

(1, 3)

In [46]:
second_matrix = np.array([[2,3], [2,3], [2,3]])

In [47]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [48]:
second_matrix.shape

(3, 2)

In [49]:
first_matrix * second_matrix

ValueError: operands could not be broadcast together with shapes (1,3) (3,2) 

In [50]:
result_matrix = first_matrix.dot(second_matrix)

In [51]:
result_matrix

array([[120, 180]])

In [52]:
result_matrix.shape

(1, 2)