In [2]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)

In [4]:
new_array

array([97, 27, 88, 25, 83, 24, 45, 98, 11, 64, 61, 83, 43, 45, 12, 37, 47,
       81, 21, 38], dtype=int32)

In [5]:
new_array > 25

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True])

In [6]:
new_array[new_array > 25]

array([97, 27, 88, 83, 45, 98, 64, 61, 83, 43, 45, 37, 47, 81, 38],
      dtype=int32)

In [7]:
new_array[new_array < 25]

array([24, 11, 12, 21], dtype=int32)

In [8]:
# transpose & reshape

In [9]:
matrix_array = np.array([[10,20], [20,30], [30,40]])

In [10]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [11]:
matrix_array.shape

(3, 2)

In [12]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array = np.random.random((6,1))

In [15]:
random_array

array([[0.9191564 ],
       [0.01242317],
       [0.03316874],
       [0.79800578],
       [0.05667677],
       [0.24813824]])

In [16]:
random_array.shape

(6, 1)

In [17]:
random_array.reshape(2,3)

array([[0.9191564 , 0.01242317, 0.03316874],
       [0.79800578, 0.05667677, 0.24813824]])

In [18]:
random_array.reshape(3,2)

array([[0.9191564 , 0.01242317],
       [0.03316874, 0.79800578],
       [0.05667677, 0.24813824]])

In [19]:
# z-score

In [20]:
data = np.array([10,12,13,15,18,25,100,105])

In [21]:
# outlier

In [22]:
mean = np.mean(data)

In [23]:
mean

np.float64(37.25)

In [24]:
data.sum() / len(data)

np.float64(37.25)

In [25]:
std = np.std(data)

In [26]:
std

np.float64(37.9333296719389)

In [27]:
z_scores = (data - mean) / std

In [29]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [30]:
z_scores[z_scores > 1]

array([1.65421809, 1.78602829])

In [31]:
data[z_scores > 1]

array([100, 105])

In [32]:
# math equations

In [36]:
# 2x + 3y = 8 and 5x + 7y = 19

In [37]:
# coefficient

In [38]:
A = np.array([[2,3], [5,7]])

In [39]:
# constant

In [40]:
b = np.array([8,19])

In [41]:
solution = np.linalg.solve(A,b)

In [42]:
solution

array([1., 2.])